import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeSwitch from "@/components/ThemeSwitch";
import NavBar from "@/components/NavBar";
import Hero from "@/components/home/Hero"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kibreab Aklilu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-28 pt-10 p-16`}>
        <header className="flex justify-end pr-10">
          <ThemeSwitch />
        </header>
        <main className="pt-10 grid grid-cols-3 gap-7">
          <aside className="col-span-1">
            <Hero />
          </aside>
          <div className="col-span-2">
            <nav>
              <NavBar />
            </nav>
            <section className="bg-common-white rounded-xl p-12 mt-8">
              {children}
            </section>
          </div>
        </main>
      </body>
    </html>
  );
}
