import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeSwitch from "@/components/ThemeSwitch";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kibreab Aklilu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-28`}>
        <header className="flex justify-end pr-10 pt-10">
          <ThemeSwitch />
        </header>
        <main className="pt-10">{children}</main>
      </body>
    </html>
  );
}
